// cogmem - Cognitive Memory
// License: MIT

package cogmem

// guidance is the operating instruction an assistant receives about cognitive
// memory. It lives here, beside the tools and the composer it describes, so the
// wording is versioned with the behaviour and is emitted only for agents that
// actually have the subsystem. The host renders it as one numbered rule in the
// identity section of the system prompt.
const guidance = `**Memory (cogmem)** - The cogmem_* tools are your long-term memory: use them to record anything worth remembering and to search for what you need. It is organized into **domains** (containers of related memories), each with a unique name. A domain is either **sticky** (included in EVERY prompt; global rules, preferences, and standing facts — the pre-existing **General** domain is sticky) or non-sticky (a topic/project, loaded only when relevant). Each memory has exactly one **type**, and the type decides whether you ever see it again. Four are standing knowledge and load into your context: **fact** (something true, and still true next month), **preference** (how the user likes things done), **rule** (a hard directive governing your output or behaviour toward the user), and **operational** (your OWN housekeeping — where you file things, how you work, a procedure you follow; the test against rule is who it serves). The fifth is different: **event** is something that happened at a point in time, or a status as of a date — a trip, a delivery, a scheduled run, "as of Sep 4 the report is pending". **Event memories are NEVER loaded into your context.** Each domain tells you how many it holds, and you retrieve them with cogmem_memory_search using include_events. Use event for anything with a timestamp or that will be stale next week: recording a recurring note as a fact puts it in every prompt forever, and that is how an assistant ends up carrying hundreds of near-identical status lines it cannot get rid of. Record with cogmem_memory_create — with no domain argument it lands in sticky **General** (always in context); pass a domain_hint or domain_id for a topic domain. A domain can auto-load by context two ways: **tool triggers** (tool-name substrings — e.g. mcp_<server> for a whole MCP server) load it when you use a matching tool, and **keyword triggers** (words/phrases) load it when one appears in the incoming message, including a scheduled (cron) message — prefer multi-word phrases so common words don't over-match. Memory also updates on its own: a background process saves and refines memories from your conversations and loads the relevant ones into each prompt — so it may include things you did not save yourself. Memories are tagged with their type and, when they did not come from you, their origin: [origin: user] means the user wrote it by hand and it outranks your own inferences. Because only relevant memories are loaded, use cogmem_memory_search to look things up before answering anything that may depend on past context you cannot currently see. Your file tools can reach the folders listed in the Workspace section above; your config files (AGENTS/SOUL/IDENTITY/USER/MEMORY) are already in this prompt — you cannot read or edit them.`

// Guidance returns the prompt text that teaches an assistant how cognitive
// memory works and how to use the cogmem_* tools. Empty for a host that does not
// wire cognitive memory; the host must not emit it for such agents.
func Guidance() string { return guidance }
